apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: toolify
  name: toolify-{{ .Values.image.version }}-hpa
  namespace: application
spec:
  maxReplicas: 50
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 35
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 30
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: toolify-{{ .Values.image.version }}