apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: toolify
  namespace: application
spec:
  hosts:
    - toolify.gowthamd.cloud
  gateways:
    - toolify
  http:
    - name: toolify
      match:
        - uri:
            prefix: /
      route:
      - destination:
          host: toolify
          port:
            number: 8000
          subset: '{{ .Values.image.version }}'
        weight: 100