apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolify
  namespace: application
spec:
  selector:
    matchLabels:
      app: toolify
  template:
    metadata:
      labels:
        app: toolify
        version: 'v2'
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: toolify
        securityContext:
          privileged: true
        image: gowthamd07101999/toolify:v1
        env: 
        - name: DATABASE_NAME
          value: "postgres"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: ""
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: SECRET_KEY
          value: 'django-insecure-g47xj&e$1^49gm3v62g0mw&o$yk=k2nn=&da2+1jk7aa4%i2w5'
        - name: DEBUG
          value: "False"
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi