
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: toolify
  namespace: application
spec:
  exportTo:
  - '*'
  host: toolify
  subsets:
    - name: v1
      labels:
        version: v1
  trafficPolicy: 
    loadBalancer:
      simple: ROUND_ROBIN