
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: toolify
  namespace: application
spec:
  exportTo:
  - '*'
  host: toolify
  subsets:
    - name: '67890'
      labels:
        version: '67890'
    - name: '12345'
      labels:
        version: '12345'
  trafficPolicy: 
    loadBalancer:
      simple: ROUND_ROBIN