apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: toolify
  namespace: application
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8000
      name: http
      protocol: HTTP
    hosts:
    - "toolify"