apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: toolify
  namespace: application
spec:
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: toolify
            routes:
            - toolify
          destinationRule:
            name: toolify
            canarySubsetName: '12345'
            stableSubsetName: '67890'