apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: toolify
  namespace: application
spec:
  hosts:
    - "*"
  gateways:
    - toolify
  http:
    - name: toolify
      match:
        - uri:
            exact: /
      route:
      - destination:
          host: toolify
          port:
            number: 8000
          subset: '12345'
        weight: 100
      - destination:
          host: toolify
          port:
            number: 8000
          subset: '67890'
        weight: 0