name: "[CI UAT] Build Docker image for toolify"
on:
  push:
    branches:
      - uat

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: docker/app
          push: false
          tags: toolify:latest  # local tag, can be anything
